spring.datasource.url=jdbc:postgresql://localhost:5432/guessanime
spring.datasource.username=guessanime
spring.datasource.password=guessanime

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

anilist.api.url=https://graphql.anilist.co